apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: auth-service
  labels:
    app: mini-arcade
    component: auth-service
spec:
  selector:
    matchLabels:
      app: mini-arcade
      component: auth-service
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 30s
