apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: mini-arcade
    component: frontend
spec:
  selector:
    app: mini-arcade
    component: frontend
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
