apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gateway
  labels:
    app: mini-arcade
    component: gateway
spec:
  selector:
    matchLabels:
      app: mini-arcade
      component: gateway
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 30s
