apiVersion: v1
kind: Service
metadata:
  name: gateway
  labels:
    app: mini-arcade
    component: gateway
spec:
  selector:
    app: mini-arcade
    component: gateway
  ports:
    - port: {{ .Values.gateway.port }}
      targetPort: {{ .Values.gateway.port }}
