{{- if .Values.ingress.rateLimit.enabled }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: mini-arcade-ratelimit
  labels:
    app: mini-arcade
spec:
  rateLimit:
    average: {{ .Values.ingress.rateLimit.average }}
    burst: {{ .Values.ingress.rateLimit.burst }}
{{- end }}
