apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: mini-arcade
    component: postgres
spec:
  selector:
    app: mini-arcade
    component: postgres
  ports:
    - port: {{ .Values.postgres.port }}
      targetPort: {{ .Values.postgres.port }}
