apiVersion: v1
kind: Service
metadata:
  name: score-service
  labels:
    app: mini-arcade
    component: score-service
spec:
  selector:
    app: mini-arcade
    component: score-service
  ports:
    - port: {{ .Values.scoreService.port }}
      targetPort: {{ .Values.scoreService.port }}
