services:

  postgres:
    image: postgres:16
    container_name: miniarcade-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - miniarcade-pgdata:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 10

  auth-service:
    build:
      context: ../auth-service
    container_name: miniarcade-auth
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/miniarcade_auth
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION_MS: ${JWT_EXPIRATION_MS}
    #Swaggerhez kell
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy

  score-service:
    build:
      context: ../score-service
    container_name: miniarcade-score
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/miniarcade_scores
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    #Swaggerhez kell
    ports:
      - "8082:8082"
    depends_on:
      postgres:
        condition: service_healthy

  gateway:
    build:
      context: ../gateway
    container_name: miniarcade-gateway
    environment:
      AUTH_SERVICE_URI: http://auth-service:8081
      SCORE_SERVICE_URI: http://score-service:8082
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
      - score-service


  frontend:
      build: ../frontend
      container_name: miniarcade-frontend
      ports:
        - "80:80"
      depends_on:
        - gateway

volumes:
  miniarcade-pgdata: